version: '3'
services:
  slurmjupyter:
        build:
            context: jupyter
            dockerfile: Dockerfile
        image: stevenrbrandt/slurm-jupyter
        container_name: headnode
        hostname: slurmjupyter
        #user: admin
        user: root
        #entrypoint: sleep infinity
        #networks:
        #    - slurm-net
        ports:
            - 443:443
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.node.type == head
        volumes:
            #- shared-vol:/home
            - /srv/nfs4/etk/home:/home
            - /etc/pki-cluster:/install
            - ./users:/users
  slurmmaster:
        build:
            context: master
            dockerfile: Dockerfile
        image: stevenrbrandt/slurm-master
        container_name: master
        hostname: slurmmaster
        user: admin
        #networks:
        #    - slurm-net
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.node.type == head
        volumes:
                #- shared-vol:/home
                - /srv/nfs4/etk/home:/home
        #ports:
        #        - 6817:6817
        #        - 6818:6818
        #        - 6819:6819
  slurmnode1:
        build:
            context: node
            dockerfile: Dockerfile
        image: stevenrbrandt/slurm-node
        container_name: node1
        hostname: slurmnode1
        user: admin
        #networks:
        #    - slurm-net
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.node.type == node1
        volumes:
                #- shared-vol:/home
                - /etk/home:/home
        links:
                - slurmmaster
  slurmnode2:
        image: stevenrbrandt/slurm-node
        container_name: node2
        hostname: slurmnode2
        user: admin
        #networks:
        #    - slurm-net
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.node.type == node2
        volumes:
                #- shared-vol:/home
                - /etk/home:/home
        links:
                - slurmmaster
  slurmnode3:
        image: stevenrbrandt/slurm-node
        container_name: node3
        hostname: slurmnode3
        user: admin
        #networks:
        #    - slurm-net
        deploy:
            replicas: 1
            placement:
                constraints:
                    - node.labels.node.type == node3
        volumes:
                #- shared-vol:/home
                - /etk/home:/home
        links:
                - slurmmaster
volumes:
    shared-vol:

#networks:
#  slurm-net:
#    external: true
