version: '3'

#volumes:
#    home_cluster:

services:

  cluster-service:
    build:
        context: .
        dockerfile: Dockerfile
    image: stevenrbrandt/et-cluster
    hostname: cluster-host
    container_name: cluster-test
    #ports:
    #  - 8888:8888
    #volumes:
    #  - home_cluster:/home
    entrypoint: sleep infinity

#  tarball-service:
#    build:
#        context: .
#        dockerfile: Dockerfile2
#    image: et-tarball
#    container_name: cluster-tarball
#    entrypoint: sleep infinity
